name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    # run external services with our job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres-12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gobank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run migrations
      uses: make migrateup

    - name: Test
      run: make test
